openapi: '3.1.0'
info:
  title: Authentication REST API
  version: 0.1.0
servers:
  - url: /api/public/users
paths:
  /login:
    post:
      description: Authenticate with login and password
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationParameters'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /register:
    post:
      description: Register with new login and password
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterParameters'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /logout:
    post:
      description: Log out from current account
      operationId: logout
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
      required:
        - username
    AuthenticationParameters:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    RegisterParameters:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
